# Generated by Django 5.1 on 2024-09-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='api_rest',
            new_name='api_restful',
        ),
    ]
