# Generated by Django 5.1 on 2024-09-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0002_rename_api_rest_api_restful'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='api_restful',
            table='api_restful',
        ),
    ]
