# Generated by Django 5.1 on 2024-09-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_restful', '0003_alter_api_restful_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_restful',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
